### PR TITLE
CBG-2201: Added LeakyBucket support to the rest tester under integration tests

### PR DESCRIPTION
**Pull request by IsaacLambat**
CBG-2201

- Added LeakyBucket support to the Rest Tester for running with integration tests when using config option
- Added collection support to the rest tester when using leaky buckets
- A package will now panic if a bucket is left unclosed instead of just logging a warning

## Pre-review checklist
- [x] Removed debug logging (`fmt.Print`, `log.Print`, ...)
- [x] Logging sensitive data? Make sure it's tagged (e.g. `base.UD(docID)`, `base.MD(dbName)`)
- [x] Updated relevant information in the API specifications (such as endpoint descriptions, schemas, ...) in `docs/api`

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [ ] `xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/675/

### CODE REVIEW

File: rest/server_context.go [hunk 1]
```diff
@@ -367,7 +367,8 @@ func GetBucketSpec(config *DatabaseConfig, serverConfig *StartupConfig) (spec ba
 // Adds a database to the ServerContext.  Attempts a read after it gets the write
 // lock to see if it's already been added by another process. If so, returns either the
 // existing DatabaseContext or an error based on the useExisting flag.
-func (sc *ServerContext) _getOrAddDatabaseFromConfig(config DatabaseConfig, useExisting, failFast bool) (*db.DatabaseContext, error) {
+// Pass in a connectFn to replace the default ConnectToBucket function. This will cause the failFast argument to be ignored
```
Comment (bbrks) [inline rest/server_context.go]: Maybe rename this function for clarity - `connectFn` implies you need to actually set up a connection.

```suggestion
// Pass in a bucketFromBucketSpecFn to replace the default ConnectToBucket function. This will cause the failFast argument to be ignored
```

File: rest/utilities_testing.go [hunk 2]
```diff
@@ -228,7 +228,24 @@ func (rt *RestTester) Bucket() base.Bucket {
...
+		if rt.useLeakyTBForDB {
+			// If using a leaky bucket, make sure it ignores attempted closures to avoid double closures panic
+			// due to closing both RestTesterServerContext and testBucket in rt.Close()
+			leakyBucket, isLeaky := base.AsLeakyBucket(testBucket)
+			if isLeaky {
+				leakyBucket.SetIgnoreClose(true)
+			} else {
+				panic("Using option useLeakyTBForDB but testBucket is not a leaky bucket")
+			}
+
```
Comment (bbrks) [inline rest/utilities_testing.go]: We can simplify to make the if only deal with the error case

```suggestion
			if !isLeaky {
				panic("Using option useLeakyTBForDB but testBucket is not a leaky bucket")
			}

			leakyBucket.SetIgnoreClose(true)
```

File: rest/utilities_testing.go [hunk 3]
```diff
@@ -228,7 +228,24 @@ func (rt *RestTester) Bucket() base.Bucket {
...
 
-		_, err = rt.RestTesterServerContext.AddDatabaseFromConfig(*rt.DatabaseConfig)
+		if rt.useLeakyTBForDB {
+			// If using a leaky bucket, make sure it ignores attempted closures to avoid double closures panic
+			// due to closing both RestTesterServerContext and testBucket in rt.Close()
+			leakyBucket, isLeaky := base.AsLeakyBucket(testBucket)
+			if isLeaky {
+				leakyBucket.SetIgnoreClose(true)
+			} else {
+				panic("Using option useLeakyTBForDB but testBucket is not a leaky bucket")
```
Comment (bbrks) [inline rest/utilities_testing.go]: Some other areas of this function use `rt.tb.Fatalf` to abort the affected test, instead of failing the entire test suite - which seems preferable.

File: rest/utilities_testing.go [hunk 4]
```diff
@@ -62,6 +62,7 @@ type RestTesterConfig struct {
 	persistentConfig                bool
 	groupID                         *string
 	createScopesAndCollections      bool // If true, will automatically create any defined scopes and collections on startup.
+	useLeakyTBForDB                 bool // If true, the leaky test bucket will be used on the database. Useful for using a LeakyBucket on the DB context for integration tests.
```
Comment (bbrks) [inline rest/utilities_testing.go]: Can this be inferred if `RestTesterConfig.TestBucket` is non-nil? (is there a situation where you _wouldn't_ want to use the leaky test bucket if you were passing one in?)

**Review by bbrks — CHANGES_REQUESTED** [review]

File: rest/utilities_testing.go (hunk 4 above)
Comment (IsaacLambat) [reply rest/utilities_testing.go]: Did try that way at first, however some tests actually rely on the DB generating the bucket and therefore failing. For example, `TestCollectionsBasicIndexQuery` which relies on the index not being created on the default collection however it does get created on the default collection when TB is passed in to the database context.

File: rest/server_context.go (hunk 1 above)
Comment (IsaacLambat) [reply rest/server_context.go]: Changed `AddDatabaseFromConfigWithConnectFn` to `AddDatabaseFromConfigWithBucket` and made it take a bucket now instead then pass that down using a `bucketFromBucketSpecFn` function.

File: rest/server_context.go [hunk 5]
```diff
@@ -72,7 +72,7 @@ type bootstrapContext struct {
 func (sc *ServerContext) CreateLocalDatabase(dbs DbConfigMap) error {
 	for _, dbConfig := range dbs {
 		dbc := dbConfig.ToDatabaseConfig()
-		_, err := sc._getOrAddDatabaseFromConfig(*dbc, false, false)
+		_, err := sc._getOrAddDatabaseFromConfig(*dbc, false, db.ConnectToBucket)
```
Comment (bbrks) [inline rest/server_context.go]: Might be nicer to continue using the `db.GetConnectToBucketFn` helper but just with a static `false` parameter - fewer places to change if `ConnectToBucket` needs to change/move.

File: db/database.go [hunk 6]
```diff
@@ -293,6 +295,14 @@ func ConnectToBucket(spec base.BucketSpec) (base.Bucket, error) {
 	return ibucket.(base.Bucket), nil
 }
 
+// GetConnectToBucketFn returns a different OpenBucketFn to connect to the bucket depending on the value of failFast
+func GetConnectToBucketFn(failFast bool) OpenBucketFn {
+	if failFast {
+		return ConnectToBucketFailFast
+	}
+	return ConnectToBucket
+}
```
Comment (bbrks) [inline db/database.go]: I think we should make these `ConnectToBucket(FailFast)?` functions private so their use is restricted - encourage people to use this `GetConnectToBucketFn`

File: rest/utilities_testing.go [hunk 7]
```diff
@@ -231,7 +230,39 @@ func (rt *RestTester) Bucket() base.Bucket {
...
 		rt.DatabaseConfig.SGReplicateEnabled = base.BoolPtr(rt.RestTesterConfig.sgReplicateEnabled)
 
-		_, err = rt.RestTesterServerContext.AddDatabaseFromConfig(*rt.DatabaseConfig)
+		if rt.RestTesterConfig.TestBucket != nil {
+			// If using a leaky bucket, make sure it ignores attempted closures to avoid double closures panic
+			// due to closing both RestTesterServerContext and testBucket in rt.Close()
+			leakyBucket, isLeaky := base.AsLeakyBucket(testBucket)
+			if isLeaky {
+				leakyBucket.SetIgnoreClose(true)
+			}
```
Comment (bbrks) [inline rest/utilities_testing.go]: Reduce scope of this to avoid accidental usage of `leakyBucket` even if `isLeaky` is false

(this suggestion makes `leakyBucket` only accessible inside the if block)

```suggestion
			if leakyBucket, isLeaky := base.AsLeakyBucket(testBucket); isLeaky {
				leakyBucket.SetIgnoreClose(true)
			}
```

File: base/util_testing.go [hunk 8]
```diff
@@ -64,6 +64,25 @@ func (tb *TestBucket) GetUnderlyingBucket() Bucket {
 	return tb.Bucket
 }
 
+// AsCollectionStore gets the underlying collection store from a bucket for test purposes
+func AsCollectionStore(t testing.TB, bucket Bucket) (*Collection, bool) {
```
Comment (bbrks) [inline base/util_testing.go]: `CollectionStore` is not what we're returning from this function (other cases return something implementing a *Store interface)

I don't think we need this to be test-specific either - @torcolvin had mentioned needing to write this function.

```suggestion
// AsCollection gets the underlying Collection from a bucket
func AsCollection(bucket Bucket) (*Collection, bool) {
```

File: rest/utilities_testing.go [hunk 9]
```diff
@@ -231,7 +230,39 @@ func (rt *RestTester) Bucket() base.Bucket {
...
+
+			// Set scopes and collections on bucket if set in DB Config
```
Comment (bbrks) [inline rest/utilities_testing.go]: The comment from `MakeBucketSpec` is clearer about this being a temporary thing

```suggestion
			// WIP: Collections Phase 1 - Grab just one scope/collection from the defined set.
			// Phase 2 (multi collection) means DatabaseContext needs a set of BucketSpec/Collections, not just one...
```

File: rest/utilities_testing.go [hunk 10]
```diff
@@ -231,7 +230,39 @@ func (rt *RestTester) Bucket() base.Bucket {
...
+				if !isCollection {
+					rt.tb.Fatalf("Could not get collection from bucket with type %T: %v", testBucket.Bucket, err)
+				}
+
+				collectionBucket.Spec.Scope = scope
+				collectionBucket.Spec.Collection = collection
+				collectionBucket.Collection = collectionBucket.Collection.Bucket().Scope(*scope).Collection(*collection)
+			}
+
+			_, err = rt.RestTesterServerContext.AddDatabaseFromConfigWithBucket(rt.tb, *rt.DatabaseConfig, testBucket.Bucket)
```
Comment (bbrks) [inline rest/utilities_testing.go:266]: should this be `collectionBucket` based on setting spec/collection above? Or doesn't it matter?

```suggestion
			_, err = rt.RestTesterServerContext.AddDatabaseFromConfigWithBucket(rt.tb, *rt.DatabaseConfig, collectionBucket)
```

**Review by bbrks — CHANGES_REQUESTED** [review]

File: rest/utilities_testing.go (hunk 10 above)
Comment (IsaacLambat) [reply rest/utilities_testing.go:266]: This would cause the leaky bucket to be lost and therefore not fire the callbacks

**Comment by bbrks** [comment]
@IsaacLambat 

Can you take a look at the build failure? Probably a break after rebasing or something

```
[2022-08-11T01:08:51.702Z] # github.com/couchbase/sync_gateway/base
[2022-08-11T01:08:51.702Z] base/collection.go:1085:6: AsCollection redeclared in this block
[2022-08-11T01:08:51.702Z] 	base/collection.go:181:6: other declaration of AsCollection
[2022-08-11T01:08:51.702Z] base/collection.go:1100:9: cannot use AsCollection(underlyingBucket) (value of type bool) as type error in return statement:
[2022-08-11T01:08:51.702Z] 	bool does not implement error (missing Error method)
```

File: base/main_test_bucket_pool.go [hunk 11]
```diff
@@ -400,11 +400,16 @@ func (tbp *TestBucketPool) printStats() {
...
 	tbp.unclosedBucketsLock.Lock()
+	unclosedBucketWarnings := ""
 	for testName, buckets := range tbp.unclosedBuckets {
 		for bucketName := range buckets {
 			tbp.Logf(ctx, "WARNING: %s left %s bucket unclosed!", testName, bucketName)
+			unclosedBucketWarnings += fmt.Sprintf("%s left %s bucket unclosed!\n", testName, bucketName)
 		}
 	}
+	if unclosedBucketWarnings != "" {
+		panic(unclosedBucketWarnings)
```
Comment (adamcfraser) [inline base/main_test_bucket_pool.go:411]: I don't recall the background for this change - is this to better catch this scenario pre-merge?

File: rest/utilities_testing.go [hunk 12]
```diff
@@ -232,7 +240,36 @@ func (rt *RestTester) Bucket() base.Bucket {
 
 		rt.DatabaseConfig.SGReplicateEnabled = base.BoolPtr(rt.RestTesterConfig.sgReplicateEnabled)
 
-		_, err = rt.RestTesterServerContext.AddDatabaseFromConfig(*rt.DatabaseConfig)
+		if rt.leakyBucketConfig != nil {
+			// Scopes and collections have to be set on the bucket being passed in for the db to use.
+			if rt.createScopesAndCollections {
```
Comment (adamcfraser) [inline rest/utilities_testing.go]: I'm not sure why this code is inside a createScopesAndCollections, unless 'createScopesAndCollections' is now equivalent to 'useScopesAndCollections' for the RestTester?

File: rest/utilities_testing.go [hunk 13]
```diff
@@ -232,7 +240,36 @@ func (rt *RestTester) Bucket() base.Bucket {
...
+				}
+				if scope != nil && collection != nil {
+					collectionBucket, err := base.AsCollection(testBucket.Bucket)
+					if err != nil {
+						rt.tb.Fatalf("Could not get collection from bucket with type %T: %v", testBucket.Bucket, err)
+					}
+
+					collectionBucket.Spec.Scope = scope
+					collectionBucket.Spec.Collection = collection
+					collectionBucket.Collection = collectionBucket.Collection.Bucket().Scope(*scope).Collection(*collection)
```
Comment (adamcfraser) [inline rest/utilities_testing.go]: What exactly is going on here?  testBucket.Bucket is initialized as a gocb Collection targeting the default collection, and if we have a named collection we're using the associated Bucket() to swap to the underlying collection to the named collection?  
Are there any allocations associated with the default collection that need to be cleaned up?  I know Collection.Close() doesn't really do any work, but it feels a bit unusual to assign collectionBucket.Collection twice in this setup.

**Review by adamcfraser — CHANGES_REQUESTED** [review]
A few questions on how we're switching from default to named collection.  I'm also wondering if this approach will be compatible with future changes to support multiple collections in a single RestTester context?

File: base/main_test_bucket_pool.go (hunk 11 above)
Comment (IsaacLambat) [reply base/main_test_bucket_pool.go:411]: Originally, this was put in when a Leaky TestBucket was to be passed in to the RT in-order to make sure the bucket was closed manually at the end of the test and can't be missed. I left this change in (even though a TB is no longer passed in) because it would be useful in general as it is quite easy to miss a bucket being left unclosed when not going through all the test logs.

File: rest/utilities_testing.go (hunk 13 above)
Comment (IsaacLambat) [reply rest/utilities_testing.go]: There are no extra allocations done when changing the scope and collection to a named scope and collection. This is because the GoCB `Scope` and `Collection` functions return the provided bucket wrapped in a GoCB `Scope` and `Collection` struct.

**Comment by IsaacLambat** [comment]
> A few questions on how we're switching from default to named collection. I'm also wondering if this approach will be compatible with future changes to support multiple collections in a single RestTester context?

The change to add scopes and collections when using a leaky bucket is a temporary measure that can be ripped out once tests are backed by collections.

**Review by adamcfraser — APPROVED** [review]
